### PR TITLE
Accept .jpeg files as well as .jpg

### PR DESCRIPTION
**Pull request by yogaraptor**
Come across this issue when using the project builder - this looked like it might be the relevant lib.

### CODE REVIEW

**Comment by chrissnyder** [comment]
Sorry @itsravenous, this repo is used more for offline uploading of subjects. To get the project builder to accept .jpegs, the code you are looking for is at https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/subject-set.cjsx#L18

**Comment by yogaraptor** [comment]
Wonderful, thanks Chris. I'll create a PR over there, unless you'd prefer I just log an issue.

**Comment by chrissnyder** [comment]
A PR would be fantastic

**Comment by brian-c** [comment]
Taken care of in #6.

**Pull request closed without merging**
